"use client";

import type { Locale } from "@mandys/i18n";
import { ErrorState, LoadingState, useToast } from "@mandys/ui";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";

import { authClient } from "../../lib/auth-client";

const operationalRoles = ["owner", "manager", "reception", "kitchen", "staff", "marketing", "accounting"] as const;
const reservationRoles = ["owner", "manager", "reception", "kitchen", "staff"] as const;
const orderRoles = ["owner", "manager", "reception", "kitchen", "staff"] as const;
const menuRoles = operationalRoles;
const stockRoles = ["owner", "manager", "kitchen", "staff", "accounting"] as const;
const eventRoles = ["owner", "manager", "reception", "marketing"] as const;
const customerRoles = ["owner", "manager", "reception"] as const;
const insightRoles = ["owner", "manager", "reception", "marketing", "accounting"] as const;
const adminRoles = ["owner", "manager"] as const;
const billingRoles = ["owner", "manager", "accounting"] as const;
const sessionRequestTimeoutMs = 8_000;
const sessionRequestAttempts = 2;
const operationalWarmups = ["menu", "reservations", "crm", "orders", "stock", "notifications"].map((service) => `/api/${service}/health`);

const copy = {
  "pt-PT": { loading: "A verificar sessão…", unavailable: "Não foi possível verificar a sessão.", retry: "Tentar novamente", dashboard: "Painel", reservations: "Reservas", orders: "Pedidos", menu: "Menu", stock: "Stock", events: "Eventos", customers: "Clientes", insights: "Insights", notifications: "Notificações", team: "Equipa", account: "A minha conta", profile: "Perfil", settings: "Operação", activity: "Atividade", billing: "Plano", data: "Dados", logout: "Sair", navigation: "Navegação", openNav: "Abrir navegação", closeNav: "Fechar navegação", skip: "Saltar para o conteúdo", signOutError: "Não foi possível terminar a sessão." },
  "pt-BR": { loading: "Verificando sessão…", unavailable: "Não foi possível verificar a sessão.", retry: "Tentar novamente", dashboard: "Painel", reservations: "Reservas", orders: "Pedidos", menu: "Cardápio", stock: "Estoque", events: "Eventos", customers: "Clientes", insights: "Insights", notifications: "Notificações", team: "Equipe", account: "Minha conta", profile: "Perfil", settings: "Operação", activity: "Atividade", billing: "Plano", data: "Dados", logout: "Sair", navigation: "Navegação", openNav: "Abrir navegação", closeNav: "Fechar navegação", skip: "Pular para o conteúdo", signOutError: "Não foi possível sair." },
  en: { loading: "Checking session…", unavailable: "We couldn't verify the session.", retry: "Try again", dashboard: "Dashboard", reservations: "Reservations", orders: "Orders", menu: "Menu", stock: "Stock", events: "Events", customers: "Customers", insights: "Insights", notifications: "Notifications", team: "Team", account: "My account", profile: "Profile", settings: "Operations", activity: "Activity", billing: "Plan", data: "Data", logout: "Sign out", navigation: "Navigation", openNav: "Open navigation", closeNav: "Close navigation", skip: "Skip to content", signOutError: "We couldn't sign you out." },
  es: { loading: "Verificando la sesión…", unavailable: "No se pudo verificar la sesión.", retry: "Intentar de nuevo", dashboard: "Panel", reservations: "Reservas", orders: "Pedidos", menu: "Menú", stock: "Stock", events: "Eventos", customers: "Clientes", insights: "Insights", notifications: "Notificaciones", team: "Equipo", account: "Mi cuenta", profile: "Perfil", settings: "Operación", activity: "Actividad", billing: "Plan", data: "Datos", logout: "Salir", navigation: "Navegación", openNav: "Abrir navegación", closeNav: "Cerrar navegación", skip: "Saltar al contenido", signOutError: "No se pudo cerrar la sesión." },
} as const satisfies Record<Locale, Record<string, string>>;

type ProtectedContextResponse = { data?: { currentRole?: string }; error?: string; message?: string };
function hasRole(role: string | null, allowed: readonly string[]) { return role !== null && allowed.includes(role); }
function dataPrefetchForHref(href: string): string | null {
  if (href.endsWith("/menu")) return "/api/menu/v1/menu";
  if (href.endsWith("/orders")) return "/api/orders/v1/orders?limit=25&offset=0";
  if (href.endsWith("/customers")) return "/api/crm/v1/customers?limit=25&offset=0";
  if (href.endsWith("/notifications")) return "/api/notifications/v1/notifications?limit=25&offset=0";
  return null;
}
async function fetchProtectedContext(): Promise<Response> { let lastError: unknown; for (let attempt = 1; attempt <= sessionRequestAttempts; attempt += 1) { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), sessionRequestTimeoutMs); try { const response = await fetch("/api/dashboard", { credentials: "include", cache: "no-store", signal: controller.signal }); if (response.status < 500 || attempt === sessionRequestAttempts) return response; lastError = new Error(`Dashboard session check returned ${response.status}`); } catch (error) { lastError = error; if (attempt === sessionRequestAttempts) throw error; } finally { window.clearTimeout(timeout); } await new Promise((resolve) => window.setTimeout(resolve, 250 * attempt)); } throw lastError ?? new Error("Dashboard session check failed"); }

export function SessionBoundary({ locale, children }: { locale: Locale; children: ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const toast = useToast(); const isLogin = pathname.endsWith("/login") || pathname.endsWith("/reset-password"); const checkedRef = useRef(false); const warmedDataRef = useRef(new Set<string>()); const warmedServicesRef = useRef(false);
  const [state, setState] = useState<"checking" | "ready" | "unavailable">(isLogin ? "ready" : "checking"); const [role, setRole] = useState<string | null>(null); const [signingOut, setSigningOut] = useState(false); const [checkRevision, setCheckRevision] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [navigating, setNavigating] = useState(false);
  useEffect(() => { setNavigating(false); setMenuOpen(false); }, [pathname]);
  useEffect(() => { if (state !== "ready" || isLogin || warmedServicesRef.current) return; warmedServicesRef.current = true; const timer = window.setTimeout(() => { for (const url of operationalWarmups) void fetch(url, { credentials: "include", cache: "no-store" }).catch(() => undefined); }, 450); return () => window.clearTimeout(timer); }, [isLogin, state]);
  useEffect(() => {
    if (isLogin) { checkedRef.current = false; setState("ready"); setRole(null); return; } if (checkedRef.current) return; checkedRef.current = true; let cancelled = false; setState("checking");
    void (async () => { try { const onboardingPath = `/${locale}/onboarding`; const loginPath = `/${locale}/login`; if (pathname.startsWith(onboardingPath)) { const sessionResult = await authClient.getSession(); if (cancelled) return; if (sessionResult.error) { setState("unavailable"); return; } if (!sessionResult.data) { router.replace(loginPath); return; } setRole(null); setState("ready"); return; } const response = await fetchProtectedContext(); const body = (await response.json().catch(() => null)) as ProtectedContextResponse | null; if (cancelled) return; if (response.status === 401 && body?.error === "TENANT_CONTEXT_REQUIRED") { router.replace(onboardingPath); return; } if (response.status === 401) { router.replace(loginPath); return; } if (!response.ok) { setState("unavailable"); return; } const activeRole = body?.data?.currentRole; if (typeof activeRole !== "string" || activeRole.length === 0) { setState("unavailable"); return; } setRole(activeRole); setState("ready"); } catch { if (!cancelled) setState("unavailable"); } })(); return () => { cancelled = true; };
  }, [checkRevision, isLogin, locale, pathname, router]);
  function retrySessionCheck() { checkedRef.current = false; setCheckRevision((value) => value + 1); }
  function warmNavigation(href: string) { router.prefetch(href); const dataUrl = dataPrefetchForHref(href); if (!dataUrl || warmedDataRef.current.has(dataUrl)) return; warmedDataRef.current.add(dataUrl); void fetch(dataUrl, { credentials: "include", cache: "no-store" }).catch(() => warmedDataRef.current.delete(dataUrl)); }
  async function signOut() { setSigningOut(true); try { await authClient.signOut(); checkedRef.current = false; warmedDataRef.current.clear(); warmedServicesRef.current = false; router.replace(`/${locale}/login`); router.refresh(); } catch { toast.error(copy[locale].signOutError); } finally { setSigningOut(false); } }
  if (state === "ready" && isLogin) return children; const c = copy[locale];
  if (state === "ready") {
    const links = [{ href: `/${locale}`, label: c.dashboard, exact: true, roles: operationalRoles }, { href: `/${locale}/reservations`, label: c.reservations, roles: reservationRoles }, { href: `/${locale}/orders`, label: c.orders, roles: orderRoles }, { href: `/${locale}/menu`, label: c.menu, roles: menuRoles }, { href: `/${locale}/stock`, label: c.stock, roles: stockRoles }, { href: `/${locale}/events`, label: c.events, roles: eventRoles }, { href: `/${locale}/customers`, label: c.customers, roles: customerRoles }, { href: `/${locale}/insights`, label: c.insights, roles: insightRoles }, { href: `/${locale}/notifications`, label: c.notifications, roles: operationalRoles }, { href: `/${locale}/account`, label: c.account, roles: operationalRoles }, { href: `/${locale}/team`, label: c.team, roles: adminRoles }, { href: `/${locale}/profile`, label: c.profile, roles: adminRoles }, { href: `/${locale}/settings`, label: c.settings, roles: adminRoles }, { href: `/${locale}/activity`, label: c.activity, roles: adminRoles }, { href: `/${locale}/billing`, label: c.billing, roles: billingRoles }, { href: `/${locale}/data`, label: c.data, roles: ["owner"] as const }].filter((link) => hasRole(role, link.roles));
    const navLink = (link: (typeof links)[number]) => { const active = link.exact ? pathname === link.href : pathname.startsWith(link.href); return <Link key={link.href} href={link.href} prefetch aria-current={active ? "page" : undefined} onClick={() => { if (!active) setNavigating(true); setMenuOpen(false); }} onMouseEnter={() => warmNavigation(link.href)} onFocus={() => warmNavigation(link.href)} className={`min-h-11 rounded-lg px-3 py-2.5 text-sm font-medium transition ${active ? "bg-[var(--mandys-foreground)] text-[var(--mandys-background)]" : "text-[var(--mandys-foreground-muted)] hover:bg-[var(--mandys-surface-muted)] hover:text-[var(--mandys-foreground)]"}`}>{link.label}</Link>; };
    return <div lang={locale} className="min-w-0"><a href="#main-content" className="sr-only fixed left-3 top-3 z-[120] rounded-lg bg-[var(--mandys-foreground)] px-4 py-3 text-[var(--mandys-background)] focus:not-sr-only">{c.skip}</a><div aria-hidden="true" className={`mandys-route-progress ${navigating ? "mandys-route-progress--active" : ""}`} /><header className="sticky top-0 z-40 border-b border-[var(--mandys-border)] bg-[var(--mandys-background)]/95 backdrop-blur"><div className="mx-auto flex w-full max-w-[1500px] items-center gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href={`/${locale}`} className="shrink-0 text-base font-bold tracking-[-0.03em]" onClick={() => setMenuOpen(false)} onMouseEnter={() => warmNavigation(`/${locale}`)} onFocus={() => warmNavigation(`/${locale}`)}>Mandy&apos;s</Link><nav aria-label="Mandy's" className="hidden min-w-0 flex-1 flex-wrap items-center gap-1 xl:flex">{links.map(navLink)}</nav><button type="button" aria-label={menuOpen ? c.closeNav : c.openNav} aria-controls="mandys-responsive-navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)} className="ml-auto inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg border border-[var(--mandys-border)] px-3 text-sm font-semibold xl:hidden">{menuOpen ? "×" : "☰"}</button><button type="button" onClick={() => void signOut()} disabled={signingOut} className="hidden min-h-11 shrink-0 rounded-lg border border-[var(--mandys-border)] px-3 py-2 text-sm font-medium disabled:opacity-60 xl:block">{signingOut ? "…" : c.logout}</button></div>{menuOpen ? <nav id="mandys-responsive-navigation" aria-label={c.navigation} className="mx-auto grid w-full max-w-[1500px] grid-cols-1 gap-1 border-t border-[var(--mandys-border)] px-4 py-3 sm:grid-cols-2 sm:px-6 lg:grid-cols-3 lg:px-8 xl:hidden">{links.map(navLink)}<button type="button" onClick={() => void signOut()} disabled={signingOut} className="min-h-11 rounded-lg border border-[var(--mandys-border)] px-3 py-2 text-left text-sm font-medium disabled:opacity-60">{signingOut ? "…" : c.logout}</button></nav> : null}</header><div id="main-content" tabIndex={-1} className="min-w-0">{children}</div></div>;
  }
  return <main className="grid min-h-screen place-items-center px-4 sm:px-6"><div className="w-full max-w-md">{state === "checking" ? <LoadingState label={c.loading} rows={2} /> : <ErrorState title={c.unavailable} description={c.unavailable} retryLabel={c.retry} onRetry={retrySessionCheck} />}</div></main>;
}
