"use client";

import type { Locale } from "@mandys/i18n";
import { Button, EmptyState, ErrorState, LoadingState, useToast } from "@mandys/ui";
import { useCallback, useEffect, useMemo, useState } from "react";

type Notification = { id: string; eventKey: string; entityType: string | null; entityId: string | null; severity: "info" | "success" | "warning" | "critical"; title: string; body: string | null; metadata: Record<string, unknown>; createdAt: string; readAt: string | null };
type NotificationsResponse = { data: { notifications: Notification[]; total: number; unread: number; pagination?: { limit: number; offset: number; hasMore: boolean } } };
type ErrorResponse = { message?: string };
const pageSize = 25;

const copy = {
  "pt-PT": { title: "Centro de notificações", subtitle: "Novas reservas, lista de espera, eventos e pedidos takeaway aparecem aqui automaticamente.", all: "Todas", unread: "Não lidas", markAll: "Marcar tudo como lido", loading: "A carregar notificações…", empty: "Não existem notificações.", emptyDesc: "Quando houver nova atividade importante, ela aparece aqui.", loadError: "Não foi possível carregar as notificações.", retry: "Tentar novamente", refresh: "Atualizar", read: "Marcar como lida", total: "Total", unreadCount: "Por ler", previous: "Anterior", next: "Seguinte", page: "Página", marked: "Notificação marcada como lida.", markedAll: "Todas as notificações foram marcadas como lidas.", updateError: "Não foi possível atualizar a notificação.", reservation: "Nova reserva recebida", waitlist: "Novo pedido na lista de espera", event: "Novo pedido de evento", order: "Novo pedido takeaway" },
  "pt-BR": { title: "Central de notificações", subtitle: "Novas reservas, lista de espera, eventos e pedidos takeaway aparecem aqui automaticamente.", all: "Todas", unread: "Não lidas", markAll: "Marcar tudo como lido", loading: "Carregando notificações…", empty: "Não há notificações.", emptyDesc: "Quando houver nova atividade importante, ela aparecerá aqui.", loadError: "Não foi possível carregar as notificações.", retry: "Tentar novamente", refresh: "Atualizar", read: "Marcar como lida", total: "Total", unreadCount: "Não lidas", previous: "Anterior", next: "Próxima", page: "Página", marked: "Notificação marcada como lida.", markedAll: "Todas as notificações foram marcadas como lidas.", updateError: "Não foi possível atualizar a notificação.", reservation: "Nova reserva recebida", waitlist: "Novo pedido na lista de espera", event: "Novo pedido de evento", order: "Novo pedido takeaway" },
  en: { title: "Notification center", subtitle: "New reservations, waitlist entries, events and takeaway orders appear here automatically.", all: "All", unread: "Unread", markAll: "Mark all as read", loading: "Loading notifications…", empty: "There are no notifications.", emptyDesc: "Important new activity will appear here.", loadError: "Notifications could not be loaded.", retry: "Try again", refresh: "Refresh", read: "Mark as read", total: "Total", unreadCount: "Unread", previous: "Previous", next: "Next", page: "Page", marked: "Notification marked as read.", markedAll: "All notifications were marked as read.", updateError: "Notification could not be updated.", reservation: "New reservation received", waitlist: "New waitlist request", event: "New event enquiry", order: "New takeaway order" },
  es: { title: "Centro de notificaciones", subtitle: "Nuevas reservas, lista de espera, eventos y pedidos takeaway aparecen aquí automáticamente.", all: "Todas", unread: "No leídas", markAll: "Marcar todo como leído", loading: "Cargando notificaciones…", empty: "No hay notificaciones.", emptyDesc: "La nueva actividad importante aparecerá aquí.", loadError: "No se pudieron cargar las notificaciones.", retry: "Intentar de nuevo", refresh: "Actualizar", read: "Marcar como leída", total: "Total", unreadCount: "Sin leer", previous: "Anterior", next: "Siguiente", page: "Página", marked: "Notificación marcada como leída.", markedAll: "Todas las notificaciones se marcaron como leídas.", updateError: "No se pudo actualizar la notificación.", reservation: "Nueva reserva recibida", waitlist: "Nueva solicitud en lista de espera", event: "Nueva solicitud de evento", order: "Nuevo pedido takeaway" },
} as const satisfies Record<Locale, Record<string, string>>;

function titleFor(eventKey: string, locale: Locale, fallback: string) { const c = copy[locale]; if (eventKey === "reservation.public_created") return c.reservation; if (eventKey === "reservation.waitlist_public_joined") return c.waitlist; if (eventKey === "event_lead.public_created") return c.event; if (eventKey === "order.public_created") return c.order; return fallback; }
async function readError(response: Response) { const body = (await response.json().catch(() => ({}))) as ErrorResponse; return body.message ?? `Request failed (${response.status})`; }

export function NotificationsBoard({ locale }: { locale: Locale }) {
  const c = copy[locale]; const toast = useToast(); const [items, setItems] = useState<Notification[]>([]); const [total, setTotal] = useState(0); const [unreadCount, setUnreadCount] = useState(0); const [unreadOnly, setUnreadOnly] = useState(false); const [page, setPage] = useState(0); const [hasMore, setHasMore] = useState(false); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }), [locale]);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { const response = await fetch(`/api/notifications/v1/notifications?limit=${pageSize}&offset=${page * pageSize}${unreadOnly ? "&unread=true" : ""}`, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error(await readError(response)); const body = (await response.json()) as NotificationsResponse; setItems(body.data.notifications); setTotal(body.data.total); setUnreadCount(body.data.unread); setHasMore(Boolean(body.data.pagination?.hasMore)); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : c.loadError); }
    finally { setLoading(false); }
  }, [c.loadError, page, unreadOnly]);
  useEffect(() => { void load(); }, [load]);

  function chooseUnread(value: boolean) { setUnreadOnly(value); setPage(0); }
  async function markRead(id: string) {
    const previousItems = items; const previousUnread = unreadCount; const target = items.find((item) => item.id === id); if (!target || target.readAt || busyId === id) return;
    const readAt = new Date().toISOString(); setBusyId(id); setUnreadCount((current) => Math.max(0, current - 1)); setItems((current) => unreadOnly ? current.filter((item) => item.id !== id) : current.map((item) => item.id === id ? { ...item, readAt } : item));
    try { const response = await fetch(`/api/notifications/v1/notifications/${id}/read`, { method: "PATCH", credentials: "include" }); if (!response.ok) throw new Error(await readError(response)); toast.success(c.marked); }
    catch (readFailure) { setItems(previousItems); setUnreadCount(previousUnread); toast.error(readFailure instanceof Error ? readFailure.message : c.updateError); }
    finally { setBusyId(null); }
  }
  async function markAll() {
    if (unreadCount === 0 || busyId === "all") return; const previousItems = items; const previousUnread = unreadCount; const readAt = new Date().toISOString(); setBusyId("all"); setUnreadCount(0); setItems((current) => unreadOnly ? [] : current.map((item) => item.readAt ? item : { ...item, readAt }));
    try { const response = await fetch("/api/notifications/v1/notifications/read-all", { method: "POST", credentials: "include" }); if (!response.ok) throw new Error(await readError(response)); toast.success(c.markedAll); if (unreadOnly) setPage(0); }
    catch (readFailure) { setItems(previousItems); setUnreadCount(previousUnread); toast.error(readFailure instanceof Error ? readFailure.message : c.updateError); }
    finally { setBusyId(null); }
  }

  return <div className="min-w-0 space-y-6" aria-busy={loading}>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h2 className="text-xl font-semibold">{c.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--mandys-foreground-muted)]">{c.subtitle}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={() => void load()} disabled={loading}>{c.refresh}</Button><Button variant="secondary" size="sm" onClick={() => void markAll()} disabled={busyId === "all" || unreadCount === 0}>{c.markAll}</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-[var(--mandys-radius-md)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-4"><div className="text-2xl font-semibold">{total}</div><div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{c.total}</div></div><div className="rounded-[var(--mandys-radius-md)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-4"><div className="text-2xl font-semibold">{unreadCount}</div><div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{c.unreadCount}</div></div></div>
    <div role="group" aria-label={c.title} className="flex flex-wrap gap-2"><button type="button" aria-pressed={!unreadOnly} onClick={() => chooseUnread(false)} className={`min-h-11 rounded-lg px-3 py-2 text-sm font-medium ${!unreadOnly ? "bg-[var(--mandys-foreground)] text-[var(--mandys-background)]" : "bg-[var(--mandys-surface-muted)]"}`}>{c.all}</button><button type="button" aria-pressed={unreadOnly} onClick={() => chooseUnread(true)} className={`min-h-11 rounded-lg px-3 py-2 text-sm font-medium ${unreadOnly ? "bg-[var(--mandys-foreground)] text-[var(--mandys-background)]" : "bg-[var(--mandys-surface-muted)]"}`}>{c.unread}</button></div>
    {loading ? <LoadingState label={c.loading} rows={4} /> : error && items.length === 0 ? <ErrorState title={c.loadError} description={error} retryLabel={c.retry} onRetry={() => void load()} /> : items.length === 0 ? <EmptyState title={c.empty} description={c.emptyDesc} /> : <div className="space-y-3">{items.map((item) => <article key={item.id} aria-busy={busyId === item.id || busyId === "all"} className={`min-w-0 rounded-[var(--mandys-radius-lg)] border p-4 sm:p-5 ${item.readAt ? "border-[var(--mandys-border)] bg-[var(--mandys-surface)]" : "border-[var(--mandys-accent)] bg-[var(--mandys-surface)]"}`}><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words font-semibold">{titleFor(item.eventKey, locale, item.title)}</h3><span className="rounded-full bg-[var(--mandys-surface-muted)] px-2 py-1 text-[11px] font-medium">{item.severity}</span></div>{item.body ? <p className="mt-2 break-words text-sm leading-6 text-[var(--mandys-foreground-muted)]">{item.body}</p> : null}<p className="mt-2 text-xs text-[var(--mandys-foreground-muted)]">{dateFormatter.format(new Date(item.createdAt))}</p></div>{!item.readAt ? <Button variant="secondary" size="sm" disabled={busyId === item.id || busyId === "all"} onClick={() => void markRead(item.id)}>{c.read}</Button> : null}</div></article>)}</div>}
    {!loading && !error && (page > 0 || hasMore) ? <nav aria-label={`${c.page} ${page + 1}`} className="flex flex-wrap items-center justify-between gap-3"><Button variant="secondary" size="sm" disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))}>{c.previous}</Button><span aria-live="polite" className="text-sm text-[var(--mandys-foreground-muted)]">{c.page} {page + 1}</span><Button variant="secondary" size="sm" disabled={!hasMore} onClick={() => setPage((value) => value + 1)}>{c.next}</Button></nav> : null}
  </div>;
}
