"use client";

import type { Locale } from "@mandys/i18n";
import { Button, EmptyState, ErrorState, LoadingState, useToast } from "@mandys/ui";
import { useCallback, useEffect, useMemo, useState } from "react";

type OrderStatus = "pending" | "accepted" | "preparing" | "ready" | "completed" | "cancelled";
type OrderItem = { id: string; menuItemId: string | null; itemName: string; unitPriceCents: number; quantity: number; lineTotalCents: number; notes: string | null };
type Order = { id: string; orderNumber: number; status: OrderStatus; fulfillmentType: string; paymentMethod: string; currency: string; subtotalCents: number; totalCents: number; scheduledFor: string | null; guestName: string; guestEmail: string | null; guestPhone: string | null; notes: string | null; source: string; createdAt: string; updatedAt: string; items: OrderItem[] };
type OrdersResponse = { data: Order[]; pagination?: { limit: number; offset: number; hasMore: boolean } };
type ErrorResponse = { message?: string };
const pageSize = 25;

const transitions: Record<OrderStatus, Array<{ status: OrderStatus; key: "accept" | "prepare" | "ready" | "complete" | "cancel" }>> = {
  pending: [{ status: "accepted", key: "accept" }, { status: "cancelled", key: "cancel" }], accepted: [{ status: "preparing", key: "prepare" }, { status: "cancelled", key: "cancel" }], preparing: [{ status: "ready", key: "ready" }, { status: "cancelled", key: "cancel" }], ready: [{ status: "completed", key: "complete" }, { status: "cancelled", key: "cancel" }], completed: [], cancelled: [],
};

const copy = {
  "pt-PT": { subtitle: "Takeaway com pagamento no levantamento. Os pedidos entram diretamente aqui e avançam pela cozinha até à entrega.", refresh: "Atualizar", loading: "A carregar pedidos…", empty: "Ainda não existem pedidos.", emptyDesc: "Os novos pedidos takeaway vão aparecer aqui automaticamente.", loadError: "Não foi possível carregar os pedidos.", retry: "Tentar novamente", previous: "Anterior", next: "Seguinte", page: "Página", updated: "Estado do pedido atualizado.", updateError: "Não foi possível atualizar o pedido.", pending: "Novo", accepted: "Aceite", preparing: "Em preparação", ready: "Pronto", completed: "Entregue", cancelled: "Cancelado", accept: "Aceitar", prepare: "Preparar", complete: "Entregue", cancel: "Cancelar", pickup: "Levantamento", pay: "Pagamento no levantamento", items: "itens", today: "Pedidos nesta página", open: "Em aberto", readyCount: "Prontos", revenue: "Valor concluído", customer: "Cliente", order: "Pedido" },
  "pt-BR": { subtitle: "Takeaway com pagamento na retirada. Os pedidos entram diretamente aqui e avançam pela cozinha até a entrega.", refresh: "Atualizar", loading: "Carregando pedidos…", empty: "Ainda não existem pedidos.", emptyDesc: "Novos pedidos takeaway vão aparecer aqui automaticamente.", loadError: "Não foi possível carregar os pedidos.", retry: "Tentar novamente", previous: "Anterior", next: "Próxima", page: "Página", updated: "Status do pedido atualizado.", updateError: "Não foi possível atualizar o pedido.", pending: "Novo", accepted: "Aceito", preparing: "Em preparação", ready: "Pronto", completed: "Entregue", cancelled: "Cancelado", accept: "Aceitar", prepare: "Preparar", complete: "Entregue", cancel: "Cancelar", pickup: "Retirada", pay: "Pagamento na retirada", items: "itens", today: "Pedidos nesta página", open: "Em aberto", readyCount: "Prontos", revenue: "Valor concluído", customer: "Cliente", order: "Pedido" },
  en: { subtitle: "Takeaway with payment at pickup. Orders arrive here and move through the kitchen until handoff.", refresh: "Refresh", loading: "Loading orders…", empty: "There are no orders yet.", emptyDesc: "New takeaway orders will appear here automatically.", loadError: "Orders could not be loaded.", retry: "Try again", previous: "Previous", next: "Next", page: "Page", updated: "Order status updated.", updateError: "Order could not be updated.", pending: "New", accepted: "Accepted", preparing: "Preparing", ready: "Ready", completed: "Completed", cancelled: "Cancelled", accept: "Accept", prepare: "Start preparing", complete: "Handed over", cancel: "Cancel", pickup: "Pickup", pay: "Pay at pickup", items: "items", today: "Orders on this page", open: "Open", readyCount: "Ready", revenue: "Completed value", customer: "Customer", order: "Order" },
  es: { subtitle: "Takeaway con pago al recoger. Los pedidos llegan directamente aquí y avanzan por cocina hasta la entrega.", refresh: "Actualizar", loading: "Cargando pedidos…", empty: "Todavía no hay pedidos.", emptyDesc: "Los nuevos pedidos takeaway aparecerán aquí automáticamente.", loadError: "No se pudieron cargar los pedidos.", retry: "Intentar de nuevo", previous: "Anterior", next: "Siguiente", page: "Página", updated: "Estado del pedido actualizado.", updateError: "No se pudo actualizar el pedido.", pending: "Nuevo", accepted: "Aceptado", preparing: "En preparación", ready: "Listo", completed: "Entregado", cancelled: "Cancelado", accept: "Aceptar", prepare: "Preparar", complete: "Entregado", cancel: "Cancelar", pickup: "Recogida", pay: "Pago al recoger", items: "artículos", today: "Pedidos en esta página", open: "Abiertos", readyCount: "Listos", revenue: "Valor completado", customer: "Cliente", order: "Pedido" },
} as const satisfies Record<Locale, Record<string, string>>;

async function readError(response: Response) { const body = (await response.json().catch(() => ({}))) as ErrorResponse; return body.message ?? `Request failed (${response.status})`; }

export function OrdersBoard({ locale }: { locale: Locale }) {
  const c = copy[locale]; const toast = useToast();
  const [orders, setOrders] = useState<Order[]>([]); const [page, setPage] = useState(0); const [hasMore, setHasMore] = useState(false);
  const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale, { dateStyle: "short", timeStyle: "short" }), [locale]);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { const response = await fetch(`/api/orders/v1/orders?limit=${pageSize}&offset=${page * pageSize}`, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error(await readError(response)); const body = (await response.json()) as OrdersResponse; setOrders(body.data); setHasMore(Boolean(body.pagination?.hasMore)); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : c.loadError); }
    finally { setLoading(false); }
  }, [c.loadError, page]);
  useEffect(() => { void load(); }, [load]);

  async function changeStatus(orderId: string, status: OrderStatus) {
    const previous = orders.find((order) => order.id === orderId); if (!previous || busyId === orderId) return;
    setBusyId(orderId); setOrders((current) => current.map((order) => order.id === orderId ? { ...order, status, updatedAt: new Date().toISOString() } : order));
    try { const response = await fetch(`/api/orders/v1/orders/${orderId}/status`, { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error(await readError(response)); toast.success(c.updated); }
    catch (statusError) { setOrders((current) => current.map((order) => order.id === orderId ? previous : order)); toast.error(statusError instanceof Error ? statusError.message : c.updateError); }
    finally { setBusyId(null); }
  }

  const todayKey = new Date().toDateString(); const today = orders.filter((order) => new Date(order.createdAt).toDateString() === todayKey).length; const open = orders.filter((order) => !["completed", "cancelled"].includes(order.status)).length; const ready = orders.filter((order) => order.status === "ready").length; const completedValue = orders.filter((order) => order.status === "completed").reduce((sum, order) => sum + order.totalCents, 0); const currency = orders[0]?.currency ?? "EUR"; const money = useMemo(() => new Intl.NumberFormat(locale, { style: "currency", currency }), [currency, locale]);

  return <div className="min-w-0 space-y-6" aria-busy={loading}>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-3xl text-sm leading-6 text-[var(--mandys-foreground-muted)]">{c.subtitle}</p><Button variant="secondary" size="sm" onClick={() => void load()} disabled={loading}>{c.refresh}</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: c.today, value: String(today) }, { label: c.open, value: String(open) }, { label: c.readyCount, value: String(ready) }, { label: c.revenue, value: money.format(completedValue / 100) }].map((card) => <div key={card.label} className="min-w-0 rounded-[var(--mandys-radius-md)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-4"><div className="text-2xl font-semibold">{card.value}</div><div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{card.label}</div></div>)}</div>
    {loading ? <LoadingState label={c.loading} rows={4} /> : error && orders.length === 0 ? <ErrorState title={c.loadError} description={error} retryLabel={c.retry} onRetry={() => void load()} /> : orders.length === 0 ? <EmptyState title={c.empty} description={c.emptyDesc} /> : <div className="grid min-w-0 gap-4 xl:grid-cols-2">{orders.map((order) => <article key={order.id} aria-busy={busyId === order.id} className="min-w-0 overflow-hidden rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-4 shadow-[var(--mandys-shadow-sm)] sm:p-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{c.order} #{order.orderNumber}</h2><span className="rounded-full bg-[var(--mandys-surface-muted)] px-2.5 py-1 text-xs font-medium">{c[order.status]}</span></div><p className="mt-1 break-words text-xs text-[var(--mandys-foreground-muted)]">{dateFormatter.format(new Date(order.createdAt))} · {c.pickup} · {c.pay}</p></div><div className="shrink-0 sm:text-right"><div className="font-semibold">{money.format(order.totalCents / 100)}</div><div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{order.items.reduce((sum, item) => sum + item.quantity, 0)} {c.items}</div></div></div>
      <div className="mt-4 border-t border-[var(--mandys-border)] pt-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--mandys-foreground-muted)]">{c.customer}</p><p className="mt-1 break-words text-sm font-medium">{order.guestName}</p>{order.guestEmail || order.guestPhone ? <p className="mt-1 break-words text-xs text-[var(--mandys-foreground-muted)]">{[order.guestEmail, order.guestPhone].filter(Boolean).join(" · ")}</p> : null}</div>
      <div className="mt-4 space-y-2">{order.items.map((item) => <div key={item.id} className="flex min-w-0 items-start justify-between gap-3 text-sm"><div className="min-w-0"><span className="break-words font-medium">{item.quantity}× {item.itemName}</span>{item.notes ? <p className="mt-0.5 break-words text-xs text-[var(--mandys-foreground-muted)]">{item.notes}</p> : null}</div><span className="shrink-0 whitespace-nowrap">{money.format(item.lineTotalCents / 100)}</span></div>)}</div>{order.notes ? <p className="mt-4 break-words rounded-md bg-[var(--mandys-surface-muted)] p-3 text-sm">{order.notes}</p> : null}
      <div className="mt-5 flex flex-wrap gap-2">{transitions[order.status].map((action) => <Button key={action.status} size="sm" variant={action.status === "cancelled" ? "secondary" : "primary"} disabled={busyId === order.id} onClick={() => void changeStatus(order.id, action.status)}>{c[action.key]}</Button>)}</div>
    </article>)}</div>}
    {!loading && !error && (page > 0 || hasMore) ? <nav aria-label={`${c.page} ${page + 1}`} className="flex flex-wrap items-center justify-between gap-3"><Button variant="secondary" size="sm" disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))}>{c.previous}</Button><span aria-live="polite" className="text-sm text-[var(--mandys-foreground-muted)]">{c.page} {page + 1}</span><Button variant="secondary" size="sm" disabled={!hasMore} onClick={() => setPage((value) => value + 1)}>{c.next}</Button></nav> : null}
  </div>;
}
