"use client";

import type { Locale } from "@mandys/i18n";
import { Button } from "@mandys/ui";
import { useCallback, useEffect, useMemo, useState } from "react";

type Ingredient = { id: string; name: string; sku: string | null; unit: "g" | "kg" | "ml" | "l" | "unit"; current_quantity: number; reorder_level: number; average_unit_cost_cents: number; is_active: boolean };
type Supplier = { id: string; name: string; email: string | null; phone: string | null; notes: string | null };
type Movement = { id: string; ingredientId: string; ingredientName: string; supplierId: string | null; supplierName: string | null; movementType: string; quantityDelta: number; unitCostCents: number | null; reference: string | null; notes: string | null; createdAt: string };
type StockResponse = { data: { ingredients: Ingredient[]; suppliers: Supplier[]; movements: Movement[]; recipes: unknown[]; lowStock: number } };
type ErrorResponse = { message?: string };

const copy = {
  "pt-PT": { subtitle: "Controle ingredientes, entradas, desperdício e fornecedores. O custo médio é recalculado nas compras e fica pronto para alimentar receitas e margens.", ingredients: "Ingredientes", low: "A repor", value: "Valor estimado", suppliers: "Fornecedores", addIngredient: "Novo ingrediente", name: "Nome", sku: "SKU", unit: "Unidade", quantity: "Stock inicial", reorder: "Nível de reposição", cost: "Custo por unidade (cêntimos)", create: "Criar", movement: "Movimento de stock", ingredient: "Ingrediente", type: "Tipo", amount: "Quantidade", supplier: "Fornecedor", reference: "Referência", notes: "Notas", apply: "Registar movimento", purchase: "Compra", waste: "Desperdício", adjustment: "Ajuste", transfer_in: "Transferência entrada", transfer_out: "Transferência saída", recipe_usage: "Consumo por receita", addSupplier: "Novo fornecedor", email: "Email", phone: "Telefone", history: "Movimentos recentes", loading: "A carregar stock…", empty: "Ainda não existem ingredientes.", refresh: "Atualizar", current: "Atual", reorderShort: "Repor em", avgCost: "Custo médio", lowBadge: "Reposição", save: "Guardar" },
  "pt-BR": { subtitle: "Controle ingredientes, entradas, desperdício e fornecedores. O custo médio é recalculado nas compras e fica pronto para alimentar receitas e margens.", ingredients: "Ingredientes", low: "A repor", value: "Valor estimado", suppliers: "Fornecedores", addIngredient: "Novo ingrediente", name: "Nome", sku: "SKU", unit: "Unidade", quantity: "Estoque inicial", reorder: "Nível de reposição", cost: "Custo por unidade (centavos)", create: "Criar", movement: "Movimento de estoque", ingredient: "Ingrediente", type: "Tipo", amount: "Quantidade", supplier: "Fornecedor", reference: "Referência", notes: "Notas", apply: "Registrar movimento", purchase: "Compra", waste: "Desperdício", adjustment: "Ajuste", transfer_in: "Transferência entrada", transfer_out: "Transferência saída", recipe_usage: "Consumo por receita", addSupplier: "Novo fornecedor", email: "E-mail", phone: "Telefone", history: "Movimentos recentes", loading: "Carregando estoque…", empty: "Ainda não existem ingredientes.", refresh: "Atualizar", current: "Atual", reorderShort: "Repor em", avgCost: "Custo médio", lowBadge: "Reposição", save: "Salvar" },
  en: { subtitle: "Control ingredients, receipts, waste and suppliers. Average cost is recalculated on purchases and becomes ready for recipes and margin analysis.", ingredients: "Ingredients", low: "Reorder", value: "Estimated value", suppliers: "Suppliers", addIngredient: "New ingredient", name: "Name", sku: "SKU", unit: "Unit", quantity: "Opening stock", reorder: "Reorder level", cost: "Unit cost (cents)", create: "Create", movement: "Stock movement", ingredient: "Ingredient", type: "Type", amount: "Quantity", supplier: "Supplier", reference: "Reference", notes: "Notes", apply: "Record movement", purchase: "Purchase", waste: "Waste", adjustment: "Adjustment", transfer_in: "Transfer in", transfer_out: "Transfer out", recipe_usage: "Recipe usage", addSupplier: "New supplier", email: "Email", phone: "Phone", history: "Recent movements", loading: "Loading stock…", empty: "There are no ingredients yet.", refresh: "Refresh", current: "Current", reorderShort: "Reorder at", avgCost: "Average cost", lowBadge: "Reorder", save: "Save" },
  es: { subtitle: "Controla ingredientes, entradas, desperdicio y proveedores. El coste medio se recalcula en las compras y queda listo para recetas y márgenes.", ingredients: "Ingredientes", low: "A reponer", value: "Valor estimado", suppliers: "Proveedores", addIngredient: "Nuevo ingrediente", name: "Nombre", sku: "SKU", unit: "Unidad", quantity: "Stock inicial", reorder: "Nivel de reposición", cost: "Coste por unidad (céntimos)", create: "Crear", movement: "Movimiento de stock", ingredient: "Ingrediente", type: "Tipo", amount: "Cantidad", supplier: "Proveedor", reference: "Referencia", notes: "Notas", apply: "Registrar movimiento", purchase: "Compra", waste: "Desperdicio", adjustment: "Ajuste", transfer_in: "Transferencia entrada", transfer_out: "Transferencia salida", recipe_usage: "Consumo por receta", addSupplier: "Nuevo proveedor", email: "Email", phone: "Teléfono", history: "Movimientos recientes", loading: "Cargando stock…", empty: "Todavía no hay ingredientes.", refresh: "Actualizar", current: "Actual", reorderShort: "Reponer en", avgCost: "Coste medio", lowBadge: "Reposición", save: "Guardar" },
} as const satisfies Record<Locale, Record<string, string>>;

const fieldClassName = "mt-1.5 min-h-11 w-full rounded-[var(--mandys-radius-sm)] border border-[var(--mandys-border)] bg-transparent px-3 outline-none focus:ring-2 focus:ring-[var(--mandys-accent)]";
async function readError(response: Response) { const body = (await response.json().catch(() => ({}))) as ErrorResponse; return body.message ?? `Request failed (${response.status})`; }

export function StockBoard({ locale }: { locale: Locale }) {
  const c = copy[locale];
  const [ingredients, setIngredients] = useState<Ingredient[]>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [movements, setMovements] = useState<Movement[]>([]);
  const [lowStock, setLowStock] = useState(0);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale, { dateStyle: "short", timeStyle: "short" }), [locale]);
  const money = useMemo(() => new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }), [locale]);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const response = await fetch("/api/stock/v1/stock", { credentials: "include", cache: "no-store" });
      if (!response.ok) throw new Error(await readError(response));
      const body = (await response.json()) as StockResponse;
      setIngredients(body.data.ingredients); setSuppliers(body.data.suppliers); setMovements(body.data.movements); setLowStock(body.data.lowStock);
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unexpected error"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  async function post(path: string, body: unknown) {
    setBusy(true); setError(null);
    try {
      const response = await fetch(`/api/stock${path}`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      if (!response.ok) throw new Error(await readError(response));
      await load();
    } catch (postError) { setError(postError instanceof Error ? postError.message : "Unexpected error"); }
    finally { setBusy(false); }
  }

  async function createIngredient(formData: FormData) {
    await post("/v1/ingredients", { name: String(formData.get("name") ?? ""), ...(formData.get("sku") ? { sku: String(formData.get("sku")) } : {}), unit: String(formData.get("unit") ?? "unit"), currentQuantity: Number(formData.get("currentQuantity") ?? 0), reorderLevel: Number(formData.get("reorderLevel") ?? 0), averageUnitCostCents: Number(formData.get("averageUnitCostCents") ?? 0) });
  }
  async function createMovement(formData: FormData) {
    await post("/v1/movements", { ingredientId: String(formData.get("ingredientId") ?? ""), movementType: String(formData.get("movementType") ?? "adjustment"), quantity: Number(formData.get("quantity") ?? 0), ...(formData.get("supplierId") ? { supplierId: String(formData.get("supplierId")) } : {}), ...(formData.get("unitCostCents") ? { unitCostCents: Number(formData.get("unitCostCents")) } : {}), ...(formData.get("reference") ? { reference: String(formData.get("reference")) } : {}), ...(formData.get("notes") ? { notes: String(formData.get("notes")) } : {}) });
  }
  async function createSupplier(formData: FormData) {
    await post("/v1/suppliers", { name: String(formData.get("name") ?? ""), ...(formData.get("email") ? { email: String(formData.get("email")) } : {}), ...(formData.get("phone") ? { phone: String(formData.get("phone")) } : {}), ...(formData.get("notes") ? { notes: String(formData.get("notes")) } : {}) });
  }

  const estimatedValue = ingredients.reduce((sum, ingredient) => sum + ingredient.current_quantity * ingredient.average_unit_cost_cents, 0);

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><p className="max-w-3xl text-sm leading-6 text-[var(--mandys-foreground-muted)]">{c.subtitle}</p><Button variant="secondary" size="sm" onClick={() => void load()} disabled={loading}>{c.refresh}</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: c.ingredients, value: ingredients.length }, { label: c.low, value: lowStock }, { label: c.value, value: money.format(estimatedValue / 100) }, { label: c.suppliers, value: suppliers.length }].map((card) => <div key={card.label} className="rounded-[var(--mandys-radius-md)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-4"><div className="text-2xl font-semibold">{card.value}</div><div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{card.label}</div></div>)}</div>
    {error ? <div className="rounded-md bg-[var(--mandys-surface-muted)] p-3 text-sm text-[var(--mandys-foreground-muted)]">{error}</div> : null}
    <div className="grid gap-5 xl:grid-cols-3">
      <section className="rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.addIngredient}</h2><form action={createIngredient} className="mt-4 space-y-3"><label className="block text-sm font-medium">{c.name}<input name="name" required maxLength={160} className={fieldClassName} /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">{c.sku}<input name="sku" maxLength={80} className={fieldClassName} /></label><label className="text-sm font-medium">{c.unit}<select name="unit" className={fieldClassName}><option value="unit">unit</option><option value="kg">kg</option><option value="g">g</option><option value="l">l</option><option value="ml">ml</option></select></label></div><div className="grid grid-cols-3 gap-3"><label className="text-sm font-medium">{c.quantity}<input name="currentQuantity" type="number" min="0" step="0.001" defaultValue="0" className={fieldClassName} /></label><label className="text-sm font-medium">{c.reorder}<input name="reorderLevel" type="number" min="0" step="0.001" defaultValue="0" className={fieldClassName} /></label><label className="text-sm font-medium">{c.cost}<input name="averageUnitCostCents" type="number" min="0" step="0.01" defaultValue="0" className={fieldClassName} /></label></div><Button type="submit" disabled={busy}>{c.create}</Button></form></section>
      <section className="rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.movement}</h2><form action={createMovement} className="mt-4 space-y-3"><label className="block text-sm font-medium">{c.ingredient}<select name="ingredientId" required className={fieldClassName}><option value="">—</option>{ingredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">{c.type}<select name="movementType" className={fieldClassName}>{["purchase","waste","adjustment","transfer_in","transfer_out","recipe_usage"].map((type) => <option key={type} value={type}>{c[type]}</option>)}</select></label><label className="text-sm font-medium">{c.amount}<input name="quantity" type="number" step="0.001" required className={fieldClassName} /></label></div><label className="block text-sm font-medium">{c.supplier}<select name="supplierId" className={fieldClassName}><option value="">—</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">{c.cost}<input name="unitCostCents" type="number" min="0" step="0.01" className={fieldClassName} /></label><label className="text-sm font-medium">{c.reference}<input name="reference" maxLength={200} className={fieldClassName} /></label></div><label className="block text-sm font-medium">{c.notes}<input name="notes" maxLength={2000} className={fieldClassName} /></label><Button type="submit" disabled={busy}>{c.apply}</Button></form></section>
      <section className="rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.addSupplier}</h2><form action={createSupplier} className="mt-4 space-y-3"><label className="block text-sm font-medium">{c.name}<input name="name" required maxLength={200} className={fieldClassName} /></label><label className="block text-sm font-medium">{c.email}<input name="email" type="email" className={fieldClassName} /></label><label className="block text-sm font-medium">{c.phone}<input name="phone" maxLength={40} className={fieldClassName} /></label><label className="block text-sm font-medium">{c.notes}<input name="notes" maxLength={2000} className={fieldClassName} /></label><Button type="submit" disabled={busy}>{c.save}</Button></form><div className="mt-5 space-y-2">{suppliers.map((supplier) => <div key={supplier.id} className="rounded-md bg-[var(--mandys-surface-muted)] p-3 text-sm"><span className="font-medium">{supplier.name}</span>{supplier.email || supplier.phone ? <div className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{[supplier.email,supplier.phone].filter(Boolean).join(" · ")}</div> : null}</div>)}</div></section>
    </div>
    <section className="rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.ingredients}</h2>{loading ? <p className="mt-4 text-sm text-[var(--mandys-foreground-muted)]">{c.loading}</p> : ingredients.length === 0 ? <p className="mt-4 text-sm text-[var(--mandys-foreground-muted)]">{c.empty}</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ingredients.map((ingredient) => { const low = ingredient.current_quantity <= ingredient.reorder_level; return <article key={ingredient.id} className="rounded-md border border-[var(--mandys-border)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{ingredient.name}</h3><p className="mt-1 text-xs text-[var(--mandys-foreground-muted)]">{ingredient.sku ?? "—"} · {ingredient.unit}</p></div>{low ? <span className="rounded-full bg-[var(--mandys-surface-muted)] px-2 py-1 text-[11px] font-medium">{c.lowBadge}</span> : null}</div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div><span className="text-[var(--mandys-foreground-muted)]">{c.current}</span><div className="mt-1 font-semibold">{ingredient.current_quantity}</div></div><div><span className="text-[var(--mandys-foreground-muted)]">{c.reorderShort}</span><div className="mt-1 font-semibold">{ingredient.reorder_level}</div></div><div><span className="text-[var(--mandys-foreground-muted)]">{c.avgCost}</span><div className="mt-1 font-semibold">{money.format(ingredient.average_unit_cost_cents / 100)}</div></div></div></article>; })}</div>}</section>
    <section className="rounded-[var(--mandys-radius-lg)] border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.history}</h2><div className="mt-4 divide-y divide-[var(--mandys-border)]">{movements.map((movement) => <div key={movement.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><div><span className="text-sm font-medium">{movement.ingredientName}</span><span className="ml-2 text-xs text-[var(--mandys-foreground-muted)]">{c[movement.movementType] ?? movement.movementType}{movement.supplierName ? ` · ${movement.supplierName}` : ""}</span></div><div className="text-right"><span className={`text-sm font-semibold ${movement.quantityDelta < 0 ? "text-[var(--mandys-foreground-muted)]" : ""}`}>{movement.quantityDelta > 0 ? "+" : ""}{movement.quantityDelta}</span><div className="text-[11px] text-[var(--mandys-foreground-muted)]">{dateFormatter.format(new Date(movement.createdAt))}</div></div></div>)}</div></section>
  </div>;
}
