"use client";

import type { Locale } from "@mandys/contracts";
import { Button } from "@mandys/ui";
import { useCallback, useEffect, useMemo, useState } from "react";

const apiBaseUrl = "/api/menu";
const supportedLocales = ["pt-PT", "pt-BR", "en", "es"] as const satisfies readonly Locale[];

type Translation = { locale: Locale; name: string; description: string | null };
type Allergen = { id: string; code: string; name: string };
type MenuItem = { id: string; sku: string | null; priceCents: number; imageUrl: string | null; isAvailable: boolean; isFeatured: boolean; sortOrder: number; translations: Translation[]; allergenIds: string[] };
type MenuCategory = { id: string; sortOrder: number; isVisible: boolean; translations: Translation[]; items: MenuItem[] };
type Menu = { id: string; internalName: string; slug: string; isPublished: boolean; translations: Translation[]; categories: MenuCategory[] };
type MenuResponse = { data: { menus: Menu[]; allergens: Allergen[] } };

type Copy = {
  intro: string; refresh: string; createMenu: string; internalName: string; slug: string; publicNames: string; create: string; creating: string;
  published: string; draft: string; publish: string; unpublish: string; category: string; addCategory: string; item: string; addItem: string; price: string;
  edit: string; save: string; cancel: string; remove: string; visible: string; hidden: string; available: string; soldOut: string; featured: string; image: string;
  allergens: string; none: string; empty: string; emptyCategory: string; emptyItem: string; confirmDeleteCategory: string; confirmDeleteItem: string;
};

const copy: Record<Locale, Copy> = {
  "pt-PT": { intro:"Gira menus, categorias e pratos que aparecem no site público.",refresh:"Atualizar",createMenu:"Criar menu",internalName:"Nome interno",slug:"Identificador",publicNames:"Nomes públicos",create:"Criar",creating:"A guardar…",published:"Publicado",draft:"Rascunho",publish:"Publicar",unpublish:"Retirar publicação",category:"Categoria",addCategory:"Adicionar categoria",item:"Prato / produto",addItem:"Adicionar item",price:"Preço (€)",edit:"Editar",save:"Guardar",cancel:"Cancelar",remove:"Eliminar",visible:"Visível",hidden:"Oculta",available:"Disponível",soldOut:"Esgotado",featured:"Destaque",image:"Imagem HTTPS",allergens:"Alergénios",none:"Nenhum",empty:"Ainda não existe nenhum menu.",emptyCategory:"Ainda não existem categorias.",emptyItem:"Ainda não existem itens nesta categoria.",confirmDeleteCategory:"Eliminar esta categoria e todos os pratos dentro dela?",confirmDeleteItem:"Eliminar este item?" },
  "pt-BR": { intro:"Gerencie cardápios, categorias e itens exibidos no site público.",refresh:"Atualizar",createMenu:"Criar cardápio",internalName:"Nome interno",slug:"Identificador",publicNames:"Nomes públicos",create:"Criar",creating:"Salvando…",published:"Publicado",draft:"Rascunho",publish:"Publicar",unpublish:"Despublicar",category:"Categoria",addCategory:"Adicionar categoria",item:"Prato / produto",addItem:"Adicionar item",price:"Preço (€)",edit:"Editar",save:"Salvar",cancel:"Cancelar",remove:"Excluir",visible:"Visível",hidden:"Oculta",available:"Disponível",soldOut:"Esgotado",featured:"Destaque",image:"Imagem HTTPS",allergens:"Alergênicos",none:"Nenhum",empty:"Ainda não existe nenhum cardápio.",emptyCategory:"Ainda não existem categorias.",emptyItem:"Ainda não existem itens nesta categoria.",confirmDeleteCategory:"Excluir esta categoria e todos os itens dentro dela?",confirmDeleteItem:"Excluir este item?" },
  en: { intro:"Manage the menus, categories and dishes shown on the public site.",refresh:"Refresh",createMenu:"Create menu",internalName:"Internal name",slug:"Identifier",publicNames:"Public names",create:"Create",creating:"Saving…",published:"Published",draft:"Draft",publish:"Publish",unpublish:"Unpublish",category:"Category",addCategory:"Add category",item:"Dish / product",addItem:"Add item",price:"Price (€)",edit:"Edit",save:"Save",cancel:"Cancel",remove:"Delete",visible:"Visible",hidden:"Hidden",available:"Available",soldOut:"Sold out",featured:"Featured",image:"HTTPS image",allergens:"Allergens",none:"None",empty:"No menu exists yet.",emptyCategory:"There are no categories yet.",emptyItem:"There are no items in this category yet.",confirmDeleteCategory:"Delete this category and every item inside it?",confirmDeleteItem:"Delete this item?" },
  es: { intro:"Gestiona los menús, categorías y platos que aparecen en la web pública.",refresh:"Actualizar",createMenu:"Crear menú",internalName:"Nombre interno",slug:"Identificador",publicNames:"Nombres públicos",create:"Crear",creating:"Guardando…",published:"Publicado",draft:"Borrador",publish:"Publicar",unpublish:"Retirar publicación",category:"Categoría",addCategory:"Añadir categoría",item:"Plato / producto",addItem:"Añadir item",price:"Precio (€)",edit:"Editar",save:"Guardar",cancel:"Cancelar",remove:"Eliminar",visible:"Visible",hidden:"Oculta",available:"Disponible",soldOut:"Agotado",featured:"Destacado",image:"Imagen HTTPS",allergens:"Alérgenos",none:"Ninguno",empty:"Todavía no existe ningún menú.",emptyCategory:"Todavía no existen categorías.",emptyItem:"Todavía no existen items en esta categoría.",confirmDeleteCategory:"¿Eliminar esta categoría y todos sus items?",confirmDeleteItem:"¿Eliminar este item?" },
};

const field = "min-h-10 w-full rounded-lg border border-[var(--mandys-border)] bg-transparent px-3 text-sm outline-none focus:ring-2 focus:ring-[var(--mandys-accent)]";
function getName(t: Translation[], locale: Locale) { return t.find(x=>x.locale===locale)?.name ?? t.find(x=>x.locale==="pt-PT")?.name ?? t[0]?.name ?? "—"; }
function readTranslations(fd: FormData, prefix: string) { return supportedLocales.map(locale=>({locale,name:String(fd.get(`${prefix}-${locale}`)??"").trim()})).filter(x=>x.name.length>0); }
async function readError(r: Response) { const b=await r.json().catch(()=>({})) as {message?:string}; return b.message ?? `Request failed (${r.status})`; }

export function MenuBoardV2({ locale }: { locale: Locale }) {
  const c=copy[locale];
  const [menus,setMenus]=useState<Menu[]>([]); const [allergens,setAllergens]=useState<Allergen[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [editingCategory,setEditingCategory]=useState<string|null>(null); const [editingItem,setEditingItem]=useState<string|null>(null);
  const money=useMemo(()=>new Intl.NumberFormat(locale,{style:"currency",currency:"EUR"}),[locale]);

  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`${apiBaseUrl}/v1/menu`,{credentials:"include",cache:"no-store"});if(!r.ok)throw new Error(await readError(r));const b=await r.json() as MenuResponse;setMenus(b.data.menus);setAllergens(b.data.allergens);}catch(e){setError(e instanceof Error?e.message:"Unexpected error");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);

  async function request(method:string,path:string,body?:unknown){setBusy(path);setError(null);try{const r=await fetch(`${apiBaseUrl}${path}`,{method,credentials:"include",headers:body!==undefined?{"content-type":"application/json"}:undefined,body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(await readError(r));await load();}catch(e){setError(e instanceof Error?e.message:"Unexpected error");}finally{setBusy(null);}}
  async function createMenu(fd:FormData){await request("POST","/v1/menu",{internalName:String(fd.get("internalName")??""),slug:String(fd.get("slug")??""),translations:readTranslations(fd,"menu")});}
  async function createCategory(menuId:string,fd:FormData){await request("POST","/v1/menu/categories",{menuId,sortOrder:0,isVisible:true,translations:readTranslations(fd,`cat-${menuId}`)});}
  async function createItem(categoryId:string,fd:FormData){const price=Number(String(fd.get("price")??"0").replace(",","."));const allergenIds=allergens.filter(a=>fd.get(`allergen-${categoryId}-${a.id}`)==="on").map(a=>a.id);await request("POST","/v1/menu/items",{categoryId,priceCents:Math.round(price*100),imageUrl:String(fd.get("imageUrl")??"").trim()||undefined,isAvailable:true,isFeatured:fd.get("featured")==="on",sortOrder:0,allergenIds,translations:readTranslations(fd,`item-${categoryId}`)});}
  async function updateCategory(category:MenuCategory,fd:FormData){await request("PATCH",`/v1/menu/categories/${category.id}`,{isVisible:fd.get("visible")==="on",sortOrder:Number(fd.get("sortOrder")??0),translations:readTranslations(fd,`edit-cat-${category.id}`)});setEditingCategory(null);}
  async function updateItem(item:MenuItem,fd:FormData){const price=Number(String(fd.get("price")??"0").replace(",","."));const allergenIds=allergens.filter(a=>fd.get(`edit-allergen-${item.id}-${a.id}`)==="on").map(a=>a.id);await request("PATCH",`/v1/menu/items/${item.id}`,{priceCents:Math.round(price*100),imageUrl:String(fd.get("imageUrl")??"").trim()||null,isAvailable:fd.get("available")==="on",isFeatured:fd.get("featured")==="on",sortOrder:Number(fd.get("sortOrder")??0),allergenIds,translations:readTranslations(fd,`edit-item-${item.id}`)});setEditingItem(null);}

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-[var(--mandys-foreground-muted)]">{c.intro}</p><Button variant="secondary" size="sm" onClick={()=>void load()} disabled={loading}>{c.refresh}</Button></div>
    {error?<div className="rounded-xl border border-[var(--mandys-danger)]/30 p-4 text-sm text-[var(--mandys-danger)]">{error}</div>:null}

    <section className="rounded-2xl border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5"><h2 className="font-semibold">{c.createMenu}</h2><form action={createMenu} className="mt-4 grid gap-3 lg:grid-cols-2">
      <label className="text-sm">{c.internalName}<input name="internalName" required minLength={2} maxLength={160} className={`${field} mt-1`}/></label><label className="text-sm">{c.slug}<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className={`${field} mt-1`}/></label>
      <div className="lg:col-span-2 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{supportedLocales.map(l=><label key={l} className="text-xs text-[var(--mandys-foreground-muted)]">{l}<input name={`menu-${l}`} required={l===locale} className={`${field} mt-1`}/></label>)}</div><div className="lg:col-span-2"><Button type="submit" disabled={busy!==null}>{busy?c.creating:c.create}</Button></div>
    </form></section>

    {loading?<div className="p-8 text-sm text-[var(--mandys-foreground-muted)]">…</div>:menus.length===0?<div className="rounded-2xl border border-dashed border-[var(--mandys-border)] p-8 text-center text-sm text-[var(--mandys-foreground-muted)]">{c.empty}</div>:menus.map(menu=><section key={menu.id} className="rounded-2xl border border-[var(--mandys-border)] bg-[var(--mandys-surface)] p-5 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold">{getName(menu.translations,locale)}</h2><span className="rounded-full bg-[var(--mandys-surface-muted)] px-2 py-1 text-xs">{menu.isPublished?c.published:c.draft}</span></div><p className="text-sm text-[var(--mandys-foreground-muted)]">{menu.internalName} · /{menu.slug}</p></div><Button variant="secondary" size="sm" disabled={busy!==null} onClick={()=>void request("PATCH",`/v1/menu/${menu.id}`,{isPublished:!menu.isPublished})}>{menu.isPublished?c.unpublish:c.publish}</Button></div>

      <div className="mt-5 space-y-4">{menu.categories.length===0?<p className="text-sm text-[var(--mandys-foreground-muted)]">{c.emptyCategory}</p>:menu.categories.map(cat=><article key={cat.id} className="rounded-xl border border-[var(--mandys-border)] p-4">
        {editingCategory===cat.id?<form action={fd=>updateCategory(cat,fd)} className="grid gap-3"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{supportedLocales.map(l=><label key={l} className="text-xs">{l}<input name={`edit-cat-${cat.id}-${l}`} defaultValue={cat.translations.find(t=>t.locale===l)?.name??""} className={`${field} mt-1`}/></label>)}</div><div className="flex flex-wrap gap-3"><label className="text-sm"><input type="checkbox" name="visible" defaultChecked={cat.isVisible}/> {c.visible}</label><label className="text-sm">Ordem <input type="number" name="sortOrder" defaultValue={cat.sortOrder} min={0} max={10000} className="ml-2 w-20 rounded border border-[var(--mandys-border)] bg-transparent px-2 py-1"/></label></div><div className="flex gap-2"><Button type="submit" size="sm">{c.save}</Button><Button type="button" size="sm" variant="secondary" onClick={()=>setEditingCategory(null)}>{c.cancel}</Button></div></form>:<div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">{getName(cat.translations,locale)}</h3><span className="text-xs text-[var(--mandys-foreground-muted)]">{cat.isVisible?c.visible:c.hidden}</span></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setEditingCategory(cat.id)}>{c.edit}</Button><button type="button" className="text-xs font-medium text-[var(--mandys-danger)]" onClick={()=>{if(confirm(c.confirmDeleteCategory))void request("DELETE",`/v1/menu/categories/${cat.id}`)}}>{c.remove}</button></div></div>}

        <div className="mt-4 grid gap-3 lg:grid-cols-2">{cat.items.length===0?<p className="text-sm text-[var(--mandys-foreground-muted)]">{c.emptyItem}</p>:cat.items.map(item=><div key={item.id} className="rounded-lg bg-[var(--mandys-surface-muted)] p-3">
          {editingItem===item.id?<form action={fd=>updateItem(item,fd)} className="space-y-3"><div className="grid gap-2 sm:grid-cols-2">{supportedLocales.map(l=><label key={l} className="text-xs">{l}<input name={`edit-item-${item.id}-${l}`} defaultValue={item.translations.find(t=>t.locale===l)?.name??""} className={`${field} mt-1`}/></label>)}</div><div className="grid gap-2 sm:grid-cols-3"><label className="text-xs">{c.price}<input name="price" type="number" min="0" step="0.01" defaultValue={(item.priceCents/100).toFixed(2)} className={`${field} mt-1`}/></label><label className="text-xs">Ordem<input name="sortOrder" type="number" min="0" max="10000" defaultValue={item.sortOrder} className={`${field} mt-1`}/></label><label className="text-xs">{c.image}<input name="imageUrl" type="url" defaultValue={item.imageUrl??""} className={`${field} mt-1`}/></label></div><div className="flex flex-wrap gap-4 text-sm"><label><input type="checkbox" name="available" defaultChecked={item.isAvailable}/> {c.available}</label><label><input type="checkbox" name="featured" defaultChecked={item.isFeatured}/> {c.featured}</label></div>{allergens.length?<fieldset><legend className="text-xs font-medium">{c.allergens}</legend><div className="mt-1 flex flex-wrap gap-3">{allergens.map(a=><label key={a.id} className="text-xs"><input type="checkbox" name={`edit-allergen-${item.id}-${a.id}`} defaultChecked={item.allergenIds.includes(a.id)}/> {a.name}</label>)}</div></fieldset>:null}<div className="flex gap-2"><Button size="sm" type="submit">{c.save}</Button><Button size="sm" type="button" variant="secondary" onClick={()=>setEditingItem(null)}>{c.cancel}</Button></div></form>:<><div className="flex justify-between gap-3"><div><p className="font-medium">{getName(item.translations,locale)}</p><p className="text-sm text-[var(--mandys-foreground-muted)]">{money.format(item.priceCents/100)} · {item.isAvailable?c.available:c.soldOut}{item.isFeatured?` · ${c.featured}`:""}</p></div><div className="flex gap-2"><button type="button" className="text-xs font-medium" onClick={()=>setEditingItem(item.id)}>{c.edit}</button><button type="button" className="text-xs font-medium text-[var(--mandys-danger)]" onClick={()=>{if(confirm(c.confirmDeleteItem))void request("DELETE",`/v1/menu/items/${item.id}`)}}>{c.remove}</button></div></div>{item.allergenIds.length?<p className="mt-2 text-xs text-[var(--mandys-foreground-muted)]">{c.allergens}: {item.allergenIds.map(id=>allergens.find(a=>a.id===id)?.name).filter(Boolean).join(", ")}</p>:null}</>}
        </div>)}</div>

        <form action={fd=>createItem(cat.id,fd)} className="mt-4 rounded-lg border border-dashed border-[var(--mandys-border)] p-3"><p className="mb-2 text-xs font-semibold uppercase tracking-wide">{c.addItem}</p><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{supportedLocales.map(l=><label key={l} className="text-xs">{l}<input name={`item-${cat.id}-${l}`} required={l===locale} className={`${field} mt-1`}/></label>)}</div><div className="mt-2 grid gap-2 sm:grid-cols-2"><label className="text-xs">{c.price}<input name="price" type="number" min="0" step="0.01" required className={`${field} mt-1`}/></label><label className="text-xs">{c.image}<input name="imageUrl" type="url" className={`${field} mt-1`}/></label></div><div className="mt-2 flex flex-wrap gap-3">{allergens.map(a=><label key={a.id} className="text-xs"><input type="checkbox" name={`allergen-${cat.id}-${a.id}`}/> {a.name}</label>)}<label className="text-xs"><input type="checkbox" name="featured"/> {c.featured}</label></div><Button size="sm" type="submit" className="mt-3">{c.addItem}</Button></form>
      </article>)}

      <form action={fd=>createCategory(menu.id,fd)} className="rounded-xl border border-dashed border-[var(--mandys-border)] p-4"><p className="mb-3 text-sm font-semibold">{c.addCategory}</p><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{supportedLocales.map(l=><label key={l} className="text-xs">{l}<input name={`cat-${menu.id}-${l}`} required={l===locale} className={`${field} mt-1`}/></label>)}</div><Button size="sm" type="submit" className="mt-3">{c.addCategory}</Button></form>
      </div>
    </section>)}
  </div>;
}
