import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.7";

const projectUrl = "https://dbfmjdissqsdhxhmqkqp.supabase.co";
const authSessionUrl = `${projectUrl}/functions/v1/mandys-auth/api/auth/get-session`;
const connectionString = Deno.env.get("SUPABASE_DB_URL");
if (!connectionString) throw new Error("SUPABASE_DB_URL is required");

const sql = postgres(connectionString, {
  prepare: false,
  max: 2,
  idle_timeout: 20,
  connect_timeout: 10,
  connection: { application_name: "mandys-events-edge", search_path: "mandys,public" },
});

type Context = { userId: string; organizationId: string; role: string };
type Result = { status?: number; body: unknown };
type EventStatus = "new" | "contacted" | "proposal_sent" | "deposit_pending" | "confirmed" | "completed" | "lost";

const transitions: Record<EventStatus, EventStatus[]> = {
  new: ["contacted", "lost"], contacted: ["proposal_sent", "lost"], proposal_sent: ["deposit_pending", "confirmed", "lost"],
  deposit_pending: ["confirmed", "lost"], confirmed: ["completed", "lost"], completed: [], lost: [],
};
const corsHeaders = { "access-control-allow-origin": "*", "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,PATCH,OPTIONS" };
function json(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff" } }); }
function fail(status: number, error: string, message: string): Result { return { status, body: { error, message } }; }
function isUuid(value: unknown): value is string { return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
function text(value: unknown, min: number, max: number): string | null { if (typeof value !== "string") return null; const next = value.trim(); return next.length >= min && next.length <= max ? next : null; }
function email(value: unknown): string | null { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string") return null; const next = value.trim().toLowerCase(); return next.length <= 254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next) ? next : null; }
function normalizeHostname(value: unknown): string | null { if (typeof value !== "string") return null; const normalized = value.trim().toLowerCase().replace(/^https?:\/\//, "").split("/")[0]?.split(":")[0]; return normalized && normalized.length <= 253 ? normalized : null; }
function integer(value: unknown, min: number, max: number): number | null { if (value === undefined || value === null || value === "") return null; const next = Number(value); return Number.isInteger(next) && next >= min && next <= max ? next : null; }
function moneyCents(value: unknown): number | null { return integer(value, 0, 100_000_000); }
function parseDate(value: unknown): Date | null { if (value === undefined || value === null || value === "") return null; const next = new Date(String(value)); return Number.isFinite(next.getTime()) ? next : null; }
async function clientHash(req: Request): Promise<string> { const raw = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || req.headers.get("cf-connecting-ip") || "unknown"; const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(raw)); return Array.from(new Uint8Array(digest)).slice(0, 12).map(value => value.toString(16).padStart(2, "0")).join(""); }
async function rateLimit(tx: any, key: string, max: number): Promise<boolean> { const rows = await tx<any[]>`insert into mandys.public_request_limits (key, window_started_at, request_count, updated_at) values (${key}, now(), 1, now()) on conflict (key) do update set request_count = case when mandys.public_request_limits.window_started_at < now() - interval '1 minute' then 1 else mandys.public_request_limits.request_count + 1 end, window_started_at = case when mandys.public_request_limits.window_started_at < now() - interval '1 minute' then now() else mandys.public_request_limits.window_started_at end, updated_at = now() returning request_count`; return Number(rows[0]?.request_count ?? 1) <= max; }
async function context(request: Request): Promise<Context | Result> { const cookie = request.headers.get("cookie"); if (!cookie) return fail(401, "UNAUTHENTICATED", "Authentication is required"); const response = await fetch(authSessionUrl, { headers: { cookie, accept: "application/json" }, cache: "no-store" }); if (!response.ok) return fail(401, "UNAUTHENTICATED", "Session is invalid or expired"); const body = await response.json().catch(() => null) as any; const userId = body?.user?.id; const organizationId = body?.session?.activeOrganizationId; if (typeof userId !== "string" || typeof organizationId !== "string") return fail(401, "TENANT_CONTEXT_REQUIRED", "Select an active restaurant organization"); const members = await sql<{ role: string }[]>`select role from mandys.member where organization_id=${organizationId} and user_id=${userId} limit 1`; const role = members[0]?.role; if (!role) return fail(403, "FORBIDDEN", "Organization membership is required"); return { userId, organizationId, role }; }
function canManage(ctx: Context) { return ["owner", "manager", "reception", "marketing"].includes(ctx.role); }
async function assertEnabled(tx: any, organizationId: string) { const rows = await tx<any[]>`select status from mandys.module_entitlements where organization_id=${organizationId} and module_key='events' limit 1`; if (!rows[0] || rows[0].status === "disabled") throw new Error("EVENTS_DISABLED"); }
async function audit(tx: any, organizationId: string, userId: string | null, action: string, entityId: string, metadata: Record<string, unknown>, ipHash?: string | null) { await tx`insert into mandys.audit_logs (organization_id, actor_user_id, action, entity_type, entity_id, ip_hash, metadata) values (${organizationId}, ${userId}, ${action}, 'event_lead', ${entityId}, ${ipHash ?? null}, ${tx.json(metadata)})`; }
async function resolvePublic(hostname: string) { const rows = await sql<any[]>`select organization_id from mandys.domains where hostname=${hostname} and verified_at is not null limit 1`; const organizationId = rows[0]?.organization_id; if (!organizationId) return null; return sql.begin(async tx => { await tx`select set_config('app.organization_id', ${organizationId}, true)`; await assertEnabled(tx, organizationId); const locations = await tx<any[]>`select id from mandys.locations where organization_id=${organizationId} and is_active=true order by created_at asc limit 1`; if (!locations[0]) return null; return { organizationId: organizationId as string, locationId: locations[0].id as string }; }).catch(error => String(error).includes("EVENTS_DISABLED") ? null : Promise.reject(error)); }
function validateLead(body: any) { const eventType = text(body?.eventType, 2, 120); const contactName = text(body?.contactName, 2, 160); const contactEmail = email(body?.contactEmail); const contactPhone = body?.contactPhone ? text(body.contactPhone, 1, 40) : null; const eventAt = parseDate(body?.eventAt); const partySize = integer(body?.partySize, 1, 10_000); const budgetMinCents = moneyCents(body?.budgetMinCents); const budgetMaxCents = moneyCents(body?.budgetMaxCents); const notes = body?.notes ? text(body.notes, 1, 4_000) : null; if (!eventType || !contactName || (body?.contactEmail && !contactEmail) || (body?.contactPhone && !contactPhone) || (body?.eventAt && !eventAt) || (body?.partySize !== undefined && body?.partySize !== "" && partySize === null) || (body?.budgetMinCents !== undefined && budgetMinCents === null) || (body?.budgetMaxCents !== undefined && budgetMaxCents === null) || (body?.notes && !notes)) return null; if (budgetMinCents !== null && budgetMaxCents !== null && budgetMaxCents < budgetMinCents) return null; return { eventType, contactName, contactEmail, contactPhone, eventAt, partySize, budgetMinCents, budgetMaxCents, notes }; }
async function list(ctx: Context, url: URL): Promise<Result> { if (!canManage(ctx)) return fail(403, "FORBIDDEN", "Your role cannot access events"); const status = url.searchParams.get("status"); const limit = Math.min(200, Math.max(1, Number(url.searchParams.get("limit") ?? 100))); if (!Number.isInteger(limit) || (status && !Object.hasOwn(transitions, status))) return fail(400, "INVALID_QUERY", "Event filters are invalid"); return sql.begin(async tx => { await tx`select set_config('app.organization_id', ${ctx.organizationId}, true)`; await assertEnabled(tx, ctx.organizationId); const rows = await tx<any[]>`select id,location_id,customer_id,status,event_type,contact_name,contact_email,contact_phone,event_at,party_size,budget_min_cents,budget_max_cents,notes,created_at,updated_at from mandys.event_leads where organization_id=${ctx.organizationId} and (${status}::text is null or status::text=${status}) order by created_at desc limit ${limit}`; return { body: { data: rows.map((row: any) => ({ id: row.id, locationId: row.location_id, customerId: row.customer_id, status: row.status, eventType: row.event_type, contactName: row.contact_name, contactEmail: row.contact_email, contactPhone: row.contact_phone, eventAt: row.event_at ? new Date(row.event_at).toISOString() : null, partySize: row.party_size, budgetMinCents: row.budget_min_cents, budgetMaxCents: row.budget_max_cents, notes: row.notes, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() })) } }; }).catch(error => String(error).includes("EVENTS_DISABLED") ? fail(403, "EVENTS_DISABLED", "The events module is not enabled") : Promise.reject(error)); }
async function createAuthenticated(ctx: Context, body: any): Promise<Result> { if (!canManage(ctx)) return fail(403, "FORBIDDEN", "Your role cannot create events"); const lead = validateLead(body); if (!lead) return fail(400, "INVALID_REQUEST", "Event lead data is invalid"); const requestedLocationId = body?.locationId ?? null; if (requestedLocationId && !isUuid(requestedLocationId)) return fail(400, "INVALID_REQUEST", "Location is invalid"); return sql.begin(async tx => { await tx`select set_config('app.organization_id', ${ctx.organizationId}, true)`; await assertEnabled(tx, ctx.organizationId); const locationRows = requestedLocationId ? await tx<any[]>`select id from mandys.locations where organization_id=${ctx.organizationId} and id=${requestedLocationId}::uuid and is_active=true limit 1` : await tx<any[]>`select id from mandys.locations where organization_id=${ctx.organizationId} and is_active=true order by created_at asc limit 1`; if (!locationRows[0]) return fail(422, "INVALID_LOCATION", "The selected location is not available"); const locationId = locationRows[0].id as string; const rows = await tx<any[]>`insert into mandys.event_leads (organization_id,location_id,status,event_type,contact_name,contact_email,contact_phone,event_at,party_size,budget_min_cents,budget_max_cents,notes) values (${ctx.organizationId},${locationId}::uuid,'new',${lead.eventType},${lead.contactName},${lead.contactEmail},${lead.contactPhone},${lead.eventAt ? lead.eventAt.toISOString() : null},${lead.partySize},${lead.budgetMinCents},${lead.budgetMaxCents},${lead.notes}) returning id,status`; const created = rows[0]; await audit(tx, ctx.organizationId, ctx.userId, "event_lead.created", created.id, { eventType: lead.eventType, locationId, partySize: lead.partySize, source: "backoffice" }); return { status: 201, body: { data: { id: created.id, status: created.status } } }; }).catch(error => String(error).includes("EVENTS_DISABLED") ? fail(403, "EVENTS_DISABLED", "The events module is not enabled") : Promise.reject(error)); }
async function createPublic(req: Request, body: any): Promise<Result> { const hostname = normalizeHostname(body?.hostname); const lead = validateLead(body); if (!hostname || !lead) return fail(400, "INVALID_REQUEST", "Event enquiry data is invalid"); const target = await resolvePublic(hostname); if (!target) return fail(404, "EVENTS_UNAVAILABLE", "Event enquiries are not available for this restaurant"); const hash = await clientHash(req); return sql.begin(async tx => { await tx`select set_config('app.organization_id', ${target.organizationId}, true)`; if (!(await rateLimit(tx, `public-event:${target.organizationId}:${hash}`, 8))) return fail(429, "RATE_LIMITED", "Too many event enquiries. Please try again shortly."); let customerId: string | null = null; if (lead.contactEmail || lead.contactPhone) { const existing = lead.contactEmail ? await tx<any[]>`select id from mandys.customers where organization_id=${target.organizationId} and lower(email)=${lead.contactEmail} limit 1` : await tx<any[]>`select id from mandys.customers where organization_id=${target.organizationId} and phone=${lead.contactPhone} limit 1`; customerId = existing[0]?.id ?? null; } if (!customerId) { const parts = lead.contactName.split(/\s+/); const firstName = parts.shift() ?? lead.contactName; const lastName = parts.join(" ") || null; const customer = await tx<any[]>`insert into mandys.customers (organization_id,first_name,last_name,email,phone) values (${target.organizationId},${firstName},${lastName},${lead.contactEmail},${lead.contactPhone}) returning id`; customerId = customer[0]?.id ?? null; } const rows = await tx<any[]>`insert into mandys.event_leads (organization_id,location_id,customer_id,status,event_type,contact_name,contact_email,contact_phone,event_at,party_size,budget_min_cents,budget_max_cents,notes) values (${target.organizationId},${target.locationId}::uuid,${customerId}::uuid,'new',${lead.eventType},${lead.contactName},${lead.contactEmail},${lead.contactPhone},${lead.eventAt ? lead.eventAt.toISOString() : null},${lead.partySize},${lead.budgetMinCents},${lead.budgetMaxCents},${lead.notes}) returning id,status`; const created = rows[0]; await audit(tx, target.organizationId, null, "event_lead.public_created", created.id, { eventType: lead.eventType, locationId: target.locationId, partySize: lead.partySize, source: "storefront" }, hash); return { status: 201, body: { data: { id: created.id, status: created.status } } }; }); }
async function changeStatus(ctx: Context, eventLeadId: string, body: any): Promise<Result> { if (!canManage(ctx)) return fail(403, "FORBIDDEN", "Your role cannot update events"); const status = typeof body?.status === "string" && Object.hasOwn(transitions, body.status) ? body.status as EventStatus : null; if (!isUuid(eventLeadId) || !status) return fail(400, "INVALID_REQUEST", "Event lead status update is invalid"); return sql.begin(async tx => { await tx`select set_config('app.organization_id', ${ctx.organizationId}, true)`; await assertEnabled(tx, ctx.organizationId); const currentRows = await tx<any[]>`select id,status from mandys.event_leads where organization_id=${ctx.organizationId} and id=${eventLeadId}::uuid limit 1`; const current = currentRows[0]; if (!current) return fail(404, "NOT_FOUND", "Event lead not found"); if (current.status === status) return { body: { data: { id: eventLeadId, status } } }; if (!(transitions[current.status as EventStatus] ?? []).includes(status)) return fail(422, "INVALID_TRANSITION", `Event lead status cannot transition from ${current.status} to ${status}`); const updated = await tx<any[]>`update mandys.event_leads set status=${status}::mandys.event_lead_status,updated_at=now() where organization_id=${ctx.organizationId} and id=${eventLeadId}::uuid and status=${current.status}::mandys.event_lead_status returning id,status`; if (!updated[0]) return fail(409, "CONCURRENT_UPDATE", "Event lead was updated by another request"); await audit(tx, ctx.organizationId, ctx.userId, "event_lead.status_changed", eventLeadId, { from: current.status, to: status }); return { body: { data: { id: eventLeadId, status } } }; }).catch(error => String(error).includes("EVENTS_DISABLED") ? fail(403, "EVENTS_DISABLED", "The events module is not enabled") : Promise.reject(error)); }
Deno.serve(async request => { if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders }); const url = new URL(request.url); if (request.method === "GET" && (url.pathname.endsWith("/health") || url.pathname.endsWith("/mandys-events"))) return json({ ok: true, service: "mandys-events" }); try { const marker = url.pathname.indexOf("/v1/"); if (marker === -1) return json({ error: "NOT_FOUND" }, 404); const path = url.pathname.slice(marker); if (request.method === "POST" && path === "/v1/public/events") { const result = await createPublic(request, await request.json().catch(() => null)); return json(result.body, result.status ?? 200); } const ctxOrError = await context(request); if ("body" in ctxOrError) return json(ctxOrError.body, ctxOrError.status ?? 400); const ctx = ctxOrError; let result: Result; if (request.method === "GET" && path === "/v1/events") result = await list(ctx, url); else if (request.method === "POST" && path === "/v1/events") result = await createAuthenticated(ctx, await request.json().catch(() => null)); else if (request.method === "PATCH" && /^\/v1\/events\/[0-9a-f-]+\/status$/i.test(path)) result = await changeStatus(ctx, path.split("/")[3] ?? "", await request.json().catch(() => null)); else result = fail(404, "NOT_FOUND", "Route not found"); return json(result.body, result.status ?? 200); } catch (error) { console.error("mandys-events error", error instanceof Error ? error.message : String(error)); return json({ error: "INTERNAL_ERROR", message: "Event operation could not be completed" }, 500); } });
