import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.7";

const projectUrl="https://dbfmjdissqsdhxhmqkqp.supabase.co";const authSessionUrl=`${projectUrl}/functions/v1/mandys-auth/api/auth/get-session`;const connectionString=Deno.env.get("SUPABASE_DB_URL");if(!connectionString)throw new Error("SUPABASE_DB_URL is required");
const sql=postgres(connectionString,{prepare:false,max:2,idle_timeout:20,connect_timeout:10,connection:{application_name:"mandys-insights-edge",search_path:"mandys,public"}});
type Context={userId:string;organizationId:string;role:string}; type Result={status?:number;body:unknown};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});} function fail(status:number,error:string,message:string):Result{return{status,body:{error,message}};}
async function context(request:Request):Promise<Context|Result>{const cookie=request.headers.get("cookie");if(!cookie)return fail(401,"UNAUTHENTICATED","Authentication is required");const response=await fetch(authSessionUrl,{headers:{cookie,accept:"application/json"},cache:"no-store"});if(!response.ok)return fail(401,"UNAUTHENTICATED","Session is invalid or expired");const body=await response.json().catch(()=>null) as any;const userId=body?.user?.id;const organizationId=body?.session?.activeOrganizationId;if(typeof userId!=="string"||typeof organizationId!=="string")return fail(401,"TENANT_CONTEXT_REQUIRED","Select an active restaurant organization");const members=await sql<{role:string}[]>`select role from mandys.member where organization_id=${organizationId} and user_id=${userId} limit 1`;const role=members[0]?.role;if(!role)return fail(403,"FORBIDDEN","Organization membership is required");return{userId,organizationId,role};}
function canRead(ctx:Context){return ["owner","manager","reception","accounting","marketing"].includes(ctx.role);}
async function assertEnabled(tx:any,ctx:Context){const rows=await tx<any[]>`select status from mandys.module_entitlements where organization_id=${ctx.organizationId} and module_key='analytics' limit 1`;if(!rows[0]||rows[0].status==="disabled")throw new Error("ANALYTICS_DISABLED");}

async function insights(ctx:Context,url:URL):Promise<Result>{if(!canRead(ctx))return fail(403,"FORBIDDEN","Your role cannot access analytics");const daysRaw=Number(url.searchParams.get("days")??30);const days=[7,30,90].includes(daysRaw)?daysRaw:30;return sql.begin(async tx=>{await tx`select set_config('app.organization_id',${ctx.organizationId},true)`;await assertEnabled(tx,ctx);const fromInterval=`${days} days`;const [settings,reservationRows,eventRows,orderRows,customerRows,menuRows,stockRows,trendRows]=await Promise.all([
  tx<any[]>`select currency,timezone from mandys.tenant_settings where organization_id=${ctx.organizationId} limit 1`,
  tx<any[]>`select count(*)::int as total,coalesce(sum(party_size),0)::int as covers,count(*) filter (where status='completed')::int as completed,count(*) filter (where status='confirmed')::int as confirmed,count(*) filter (where status='no_show')::int as no_show,count(*) filter (where status='cancelled')::int as cancelled from mandys.reservations where organization_id=${ctx.organizationId} and starts_at>=now()-${fromInterval}::interval`,
  tx<any[]>`select count(*)::int as total,count(*) filter (where status in ('confirmed','completed'))::int as won,count(*) filter (where status='lost')::int as lost,coalesce(sum(coalesce(budget_max_cents,budget_min_cents,0)) filter (where status not in ('lost','completed')),0)::bigint as pipeline_cents from mandys.event_leads where organization_id=${ctx.organizationId} and created_at>=now()-${fromInterval}::interval`,
  tx<any[]>`select count(*)::int as total,count(*) filter (where status='completed')::int as completed,count(*) filter (where status='cancelled')::int as cancelled,coalesce(sum(total_cents) filter (where status='completed'),0)::bigint as revenue_cents,coalesce(avg(total_cents) filter (where status='completed'),0)::numeric as average_ticket_cents from mandys.orders where organization_id=${ctx.organizationId} and created_at>=now()-${fromInterval}::interval`,
  tx<any[]>`select count(*)::int as total,count(*) filter (where created_at>=now()-${fromInterval}::interval)::int as new_customers,(select count(*)::int from (select customer_id from mandys.reservations where organization_id=${ctx.organizationId} and customer_id is not null group by customer_id having count(*)>=2) r) as returning_customers from mandys.customers where organization_id=${ctx.organizationId}`,
  tx<any[]>`select count(*)::int as total_items,count(*) filter (where mi.is_available)::int as available_items,count(distinct m.id) filter (where m.is_published)::int as published_menus from mandys.menu_items mi join mandys.menu_categories mc on mc.organization_id=mi.organization_id and mc.id=mi.category_id join mandys.menus m on m.organization_id=mi.organization_id and m.id=mc.menu_id where mi.organization_id=${ctx.organizationId}`,
  tx<any[]>`select count(*) filter (where is_active)::int as ingredients,count(*) filter (where is_active and current_quantity<=reorder_level)::int as low_stock,coalesce(sum(current_quantity*average_unit_cost_cents) filter (where is_active),0)::numeric as estimated_value_cents from mandys.ingredients where organization_id=${ctx.organizationId}`,
  tx<any[]>`with days as (select generate_series((current_date-${days-1}::int),current_date,'1 day'::interval)::date as day), r as (select (starts_at at time zone coalesce((select timezone from mandys.tenant_settings where organization_id=${ctx.organizationId} limit 1),'Europe/Lisbon'))::date as day,count(*)::int as reservations,coalesce(sum(party_size),0)::int as covers from mandys.reservations where organization_id=${ctx.organizationId} and starts_at>=current_date-${days-1}::int group by 1), o as (select (created_at at time zone coalesce((select timezone from mandys.tenant_settings where organization_id=${ctx.organizationId} limit 1),'Europe/Lisbon'))::date as day,count(*) filter (where status<>'cancelled')::int as orders,coalesce(sum(total_cents) filter (where status='completed'),0)::bigint as revenue_cents from mandys.orders where organization_id=${ctx.organizationId} and created_at>=current_date-${days-1}::int group by 1), e as (select (created_at at time zone coalesce((select timezone from mandys.tenant_settings where organization_id=${ctx.organizationId} limit 1),'Europe/Lisbon'))::date as day,count(*)::int as event_leads from mandys.event_leads where organization_id=${ctx.organizationId} and created_at>=current_date-${days-1}::int group by 1) select d.day::text,coalesce(r.reservations,0)::int as reservations,coalesce(r.covers,0)::int as covers,coalesce(o.orders,0)::int as orders,coalesce(o.revenue_cents,0)::bigint as revenue_cents,coalesce(e.event_leads,0)::int as event_leads from days d left join r using(day) left join o using(day) left join e using(day) order by d.day asc`,
]);const reservations=reservationRows[0]??{};const events=eventRows[0]??{};const orders=orderRows[0]??{};const customers=customerRows[0]??{};const menu=menuRows[0]??{};const stock=stockRows[0]??{};const noShowRate=Number(reservations.total??0)>0?Number(reservations.no_show??0)/Number(reservations.total):0;const eventWinRate=Number(events.total??0)>0?Number(events.won??0)/Number(events.total):0;return{body:{data:{days,currency:settings[0]?.currency??"EUR",timezone:settings[0]?.timezone??"Europe/Lisbon",reservations:{total:Number(reservations.total??0),covers:Number(reservations.covers??0),completed:Number(reservations.completed??0),confirmed:Number(reservations.confirmed??0),cancelled:Number(reservations.cancelled??0),noShow:Number(reservations.no_show??0),noShowRate},events:{total:Number(events.total??0),won:Number(events.won??0),lost:Number(events.lost??0),pipelineCents:Number(events.pipeline_cents??0),winRate:eventWinRate},orders:{total:Number(orders.total??0),completed:Number(orders.completed??0),cancelled:Number(orders.cancelled??0),revenueCents:Number(orders.revenue_cents??0),averageTicketCents:Number(orders.average_ticket_cents??0)},customers:{total:Number(customers.total??0),newCustomers:Number(customers.new_customers??0),returningCustomers:Number(customers.returning_customers??0)},menu:{totalItems:Number(menu.total_items??0),availableItems:Number(menu.available_items??0),publishedMenus:Number(menu.published_menus??0)},stock:{ingredients:Number(stock.ingredients??0),lowStock:Number(stock.low_stock??0),estimatedValueCents:Number(stock.estimated_value_cents??0)},trend:trendRows.map((row:any)=>({day:row.day,reservations:Number(row.reservations),covers:Number(row.covers),orders:Number(row.orders),revenueCents:Number(row.revenue_cents),eventLeads:Number(row.event_leads)}))}}};}).catch(error=>String(error).includes("ANALYTICS_DISABLED")?fail(403,"ANALYTICS_DISABLED","The analytics module is not enabled"):Promise.reject(error));}

Deno.serve(async request=>{const url=new URL(request.url);if(request.method==="GET"&&(url.pathname.endsWith("/health")||url.pathname.endsWith("/mandys-insights")))return json({ok:true,service:"mandys-insights"});try{const ctxOrError=await context(request);if("body" in ctxOrError)return json(ctxOrError.body,ctxOrError.status??400);const marker=url.pathname.indexOf("/v1/");if(marker===-1)return json({error:"NOT_FOUND"},404);const path=url.pathname.slice(marker);const result=request.method==="GET"&&path==="/v1/insights"?await insights(ctxOrError,url):fail(404,"NOT_FOUND","Route not found");return json(result.body,result.status??200);}catch(error){console.error("mandys-insights error",error instanceof Error?error.message:String(error));return json({error:"INTERNAL_ERROR",message:"Insights could not be loaded"},500);}});
