import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.7";

const projectUrl = "https://dbfmjdissqsdhxhmqkqp.supabase.co";
const authSessionUrl = `${projectUrl}/functions/v1/mandys-auth/api/auth/get-session`;
const connectionString = Deno.env.get("SUPABASE_DB_URL");
if (!connectionString) throw new Error("SUPABASE_DB_URL is required");
const sql = postgres(connectionString,{prepare:false,max:2,idle_timeout:20,connect_timeout:10,connection:{application_name:"mandys-retention-edge",search_path:"mandys,public"}});
type Ctx={userId:string;organizationId:string;role:string}; type Result={status?:number;body:unknown};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});} function fail(status:number,error:string,message:string):Result{return{status,body:{error,message}};}
async function context(request:Request):Promise<Ctx|Result>{const cookie=request.headers.get("cookie");if(!cookie)return fail(401,"UNAUTHENTICATED","Authentication is required");const r=await fetch(authSessionUrl,{headers:{cookie,accept:"application/json"},cache:"no-store"});if(!r.ok)return fail(401,"UNAUTHENTICATED","Session is invalid or expired");const b=await r.json().catch(()=>null) as any;const userId=b?.user?.id,organizationId=b?.session?.activeOrganizationId;if(typeof userId!=="string"||typeof organizationId!=="string")return fail(401,"TENANT_CONTEXT_REQUIRED","Select an active restaurant organization");const rows=await sql<{role:string}[]>`select role from mandys.member where organization_id=${organizationId} and user_id=${userId} limit 1`;if(!rows[0])return fail(403,"FORBIDDEN","Organization membership is required");return{userId,organizationId,role:rows[0].role};}
function parse(v:unknown){if(v===null||v==="")return null;if(typeof v!=="number"||!Number.isInteger(v)||v<30||v>3650)return undefined;return v;}
function policy(row:any){return{customerDataRetentionDays:row.customer_data_retention_days===null?null:Number(row.customer_data_retention_days),auditLogRetentionDays:row.audit_log_retention_days===null?null:Number(row.audit_log_retention_days),notificationRetentionDays:row.notification_retention_days===null?null:Number(row.notification_retention_days)}}
async function getPolicy(ctx:Ctx):Promise<Result>{if(ctx.role!=="owner")return fail(403,"FORBIDDEN","Only an organization owner can manage retention policy");return sql.begin(async tx=>{await tx`select set_config('app.organization_id',${ctx.organizationId},true)`;const rows=await tx<any[]>`select customer_data_retention_days,audit_log_retention_days,notification_retention_days from mandys.tenant_settings where organization_id=${ctx.organizationId} limit 1`;return rows[0]?{body:{data:policy(rows[0])}}:fail(404,"SETTINGS_NOT_FOUND","Tenant settings were not found");});}
async function putPolicy(ctx:Ctx,request:Request):Promise<Result>{if(ctx.role!=="owner")return fail(403,"FORBIDDEN","Only an organization owner can manage retention policy");const body=await request.json().catch(()=>null) as any;if(!body)return fail(400,"INVALID_REQUEST","A JSON retention policy is required");const customer=parse(body.customerDataRetentionDays),audit=parse(body.auditLogRetentionDays),notifications=parse(body.notificationRetentionDays);if(customer===undefined||audit===undefined||notifications===undefined)return fail(400,"INVALID_RETENTION_POLICY","Retention values must be blank/null or whole days between 30 and 3650");return sql.begin(async tx=>{await tx`select set_config('app.organization_id',${ctx.organizationId},true)`;const rows=await tx<any[]>`update mandys.tenant_settings set customer_data_retention_days=${customer},audit_log_retention_days=${audit},notification_retention_days=${notifications},updated_at=now() where organization_id=${ctx.organizationId} returning customer_data_retention_days,audit_log_retention_days,notification_retention_days`;if(!rows[0])return fail(404,"SETTINGS_NOT_FOUND","Tenant settings were not found");const saved=policy(rows[0]);await tx`insert into mandys.audit_logs (organization_id,actor_user_id,action,entity_type,entity_id,metadata) values (${ctx.organizationId},${ctx.userId},'data.retention_updated','tenant_settings',${ctx.organizationId},${tx.json(saved)})`;return{body:{data:saved}};});}
Deno.serve(async request=>{const url=new URL(request.url);if(request.method==="GET"&&(url.pathname.endsWith("/health")||url.pathname.endsWith("/mandys-retention")))return json({ok:true,service:"mandys-retention"});try{const ctx=await context(request);if("body" in ctx)return json(ctx.body,ctx.status??400);const marker=url.pathname.indexOf("/v1/");if(marker===-1)return json({error:"NOT_FOUND"},404);const path=url.pathname.slice(marker);const result=path==="/v1/retention"&&request.method==="GET"?await getPolicy(ctx):path==="/v1/retention"&&request.method==="PUT"?await putPolicy(ctx,request):fail(404,"NOT_FOUND","Route not found");return json(result.body,result.status??200);}catch(error){console.error("mandys-retention error",error instanceof Error?error.message:String(error));return json({error:"INTERNAL_ERROR",message:"Retention policy could not be processed"},500);}});
